#!/data/data/com.termux/files/usr/bin/bash
# fix_package_name.sh — rewrites the Android applicationId/namespace/package
# from the old suspended package to the new one, everywhere it's hardcoded
# in the CI patch scripts.
#
# Usage:
#   cd ~/hc_fix_build   # adjust path to your repo checkout
#   bash fix_package_name.sh

set -euo pipefail

OLD_PKG="com.halalcalorie.app"
NEW_PKG="com.ihsanstudio.halalcalorie"
OLD_PATH="com/halalcalorie/app"
NEW_PATH="com/ihsanstudio/halalcalorie"

FILES=("patch_android.py" "patch_gradle.py")

echo "== Package rename: $OLD_PKG -> $NEW_PKG =="
echo ""

for f in "${FILES[@]}"; do
  if [ ! -f "$f" ]; then
    echo "SKIP: $f not found in $(pwd)"
    continue
  fi

  cp "$f" "$f.bak"

  BEFORE=$(grep -c "$OLD_PKG\|$OLD_PATH" "$f" || true)

  # dotted form: namespace/applicationId/package statements + print strings
  sed -i "s#${OLD_PKG}#${NEW_PKG}#g" "$f"
  # slash form: kotlin source directory path
  sed -i "s#${OLD_PATH}#${NEW_PATH}#g" "$f"

  AFTER=$(grep -c "$OLD_PKG\|$OLD_PATH" "$f" || true)

  echo "-- $f --"
  echo "   occurrences before: $BEFORE"
  echo "   occurrences after:  $AFTER"
  echo "   backup saved:       $f.bak"
  echo ""
done

echo "== Cleaning any stale compiled Kotlin dir from the old package =="
OLD_KT_DIR="android/app/src/main/kotlin/com/halalcalorie/app"
if [ -d "$OLD_KT_DIR" ]; then
  rm -rf "$OLD_KT_DIR"
  echo "removed leftover $OLD_KT_DIR"
else
  echo "no leftover $OLD_KT_DIR found (fine, it's regenerated by patch_android.py on next build)"
fi

echo ""
echo "== Sanity check: any remaining references to old package in the repo =="
grep -rn "$OLD_PKG" --include="*.py" --include="*.gradle" --include="*.kt" --include="*.xml" . 2>/dev/null \
  | grep -v "\.bak:" || echo "none found — clean"

echo ""
echo "== Manual steps still needed (not fixable by this script) =="
echo "1. If you use Firebase (google-services.json is pulled from the"
echo "   GOOGLE_SERVICES_JSON GitHub secret), update that secret's JSON"
echo "   so its package_name field matches: $NEW_PKG"
echo "   Otherwise Firebase init will silently mismatch at runtime."
echo "2. patch_gradle.py also has an earlier unrelated line:"
echo "     applicationId \"{NEW_ID}\""
echo "   That looks like a leftover placeholder (not an f-string, so it"
echo "   writes the literal text {NEW_ID} if that code path runs before"
echo "   the block this script just fixed). Worth reviewing separately —"
echo "   left untouched here since I can't be sure of its intended use."
echo "3. Commit and push, then trigger a fresh CI build — the .aab it"
echo "   produces should now report applicationId $NEW_PKG."
