
import sys
errors = []

def patch(fpath, old, new, label):
    with open(fpath, "r", encoding="utf-8") as f:
        src = f.read()
    n = src.count(old)
    if n == 0:
        errors.append(f"[{label}] anchor not found in {fpath}")
        return
    if n > 1:
        errors.append(f"[{label}] anchor not unique ({n}x) in {fpath}")
        return
    with open(fpath, "w", encoding="utf-8") as f:
        f.write(src.replace(old, new, 1))
    print(f"  [+] {label}")

HOME    = "lib/features/home/home_screen.dart"
ONBOARD = "lib/features/onboarding/onboarding_screen.dart"

# ── Fix 1: _cd() — broken string interpolation ───────────────────────
print("\n── Fix 1: _cd() literal ${h} / ${m} → real Dart interpolation ──────")

patch(HOME,
    "  String _cd(int th, int tm) {\n"
    "    final nowMins = now.hour * 60 + now.minute;\n"
    "    var diff = th * 60 + tm - nowMins;\n"
    "    if (diff <= 0) diff += 24 * 60;\n"
    "    final h = diff ~/ 60; final m = diff % 60;\n"
    "    return h == 0 ? '\\${m}\u062f' : '\\${h}\u0633 \\${m}\u062f';\n"
    "  }",
    "  String _cd(int th, int tm) {\n"
    "    final nowMins = now.hour * 60 + now.minute;\n"
    "    var diff = th * 60 + tm - nowMins;\n"
    "    if (diff <= 0) diff += 24 * 60;\n"
    "    final h = diff ~/ 60; final m = diff % 60;\n"
    "    if (isAr) {\n"
    "      return h == 0 ? '${m}\u062f' : '${h}\u0633 ${m}\u062f';\n"
    "    } else {\n"
    "      return h == 0 ? '${m}m' : '${h}h ${m}m';\n"
    "    }\n"
    "  }",
    "home: _cd bilingual interpolation fix")

# ── Fix 2: 'Day \$day ★' literal in progress bar label ───────────────
print("\n── Fix 2: progress bar 'Day \\$day' → 'Day $day' ────────────────────")

patch(HOME,
    "                    Text(t('\u0627\u0644\u064a\u0648\u0645 \\$day', 'Day \\$day \u2605'),",
    "                    Text(t('\u0627\u0644\u064a\u0648\u0645 $day', 'Day $day \u2605'),",
    "home: progress bar day label interpolation")

# ── Fix 3: _SummaryPage — add lang + bilingual text ──────────────────
print("\n── Fix 3a: _SummaryPage add lang field + ctor param ─────────────────")

patch(ONBOARD,
    "class _SummaryPage extends StatelessWidget {\n"
    "  final String gender;\n"
    "  final int age, goalIdx, activityIdx;\n"
    "  final double height, weight;\n"
    "  final bool isDark;\n"
    "  const _SummaryPage({\n"
    "    required this.gender, required this.age,\n"
    "    required this.height, required this.weight,\n"
    "    required this.goalIdx, required this.activityIdx,\n"
    "    required this.isDark,\n"
    "  });",
    "class _SummaryPage extends StatelessWidget {\n"
    "  final String gender, lang;\n"
    "  final int age, goalIdx, activityIdx;\n"
    "  final double height, weight;\n"
    "  final bool isDark;\n"
    "  const _SummaryPage({\n"
    "    required this.gender, required this.lang, required this.age,\n"
    "    required this.height, required this.weight,\n"
    "    required this.goalIdx, required this.activityIdx,\n"
    "    required this.isDark,\n"
    "  });",
    "onboarding: _SummaryPage lang field")

print("\n── Fix 3b: _SummaryPage.build() — bilingual all text ────────────────")

# Replace the hardcoded Arabic build body
patch(ONBOARD,
    "  Widget build(BuildContext context) {\n"
    "    final isMale = gender == 'brothers';\n"
    "    final card   = isDark ? const Color(0xFF161B22) : Colors.white;\n"
    "    final border = isDark ? const Color(0xFF21262D) : const Color(0xFFE8E4DF);\n"
    "\n"
    "    // Quick BMI calculation\n"
    "    final hM  = height / 100;\n"
    "    final bmi = weight / (hM * hM);\n"
    "    final bmiColor = bmi < 18.5 ? AppColors.waterBlue\n"
    "      : bmi < 25 ? AppColors.halalGreen\n"
    "      : bmi < 30 ? AppColors.doubtOrange\n"
    "      : AppColors.haramRed;\n"
    "\n"
    "    // Calorie estimate\n"
    "    final bmr = isMale\n"
    "      ? 10 * weight + 6.25 * height - 5 * age + 5\n"
    "      : 10 * weight + 6.25 * height - 5 * age - 161;\n"
    "    final acts = ActivityLevel.values;\n"
    "    final mult = acts[activityIdx.clamp(0, acts.length - 1)].multiplier;\n"
    "    final kcal = (bmr * mult).round();\n"
    "\n"
    "    return SingleChildScrollView(\n"
    "      padding: const EdgeInsets.fromLTRB(24, 8, 24, 24),\n"
    "      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [\n"
    "\n"
    "        // Header\n"
    "        TweenAnimationBuilder<double>(\n"
    "          tween: Tween(begin: 0.0, end: 1.0),\n"
    "          duration: const Duration(milliseconds: 500),\n"
    "          curve: Curves.easeOut,\n"
    "          builder: (_, v, child) => Opacity(opacity: v,\n"
    "            child: Transform.translate(offset: Offset(0, 20 * (1 - v)), child: child)),\n"
    "          child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [\n"
    "            Text('\U0001f389', style: const TextStyle(fontSize: 44)),\n"
    "            const SizedBox(height: 8),\n"
    "            Text('\u0643\u0644 \u0634\u064a\u0621 \u062c\u0627\u0647\u0632!', style: TextStyle(\n"
    "              fontFamily: 'Cairo', fontSize: 28, fontWeight: FontWeight.w900,\n"
    "              color: isDark ? Colors.white : const Color(0xFF1F2A1F),\n"
    "            )),\n"
    "            Text('\u0645\u0644\u0641\u0643 \u0627\u0644\u0634\u062e\u0635\u064a \u0645\u062d\u0633\u0648\u0628', style: TextStyle(\n"
    "              fontFamily: 'Cairo', fontSize: 13,\n"
    "              color: isDark ? const Color(0xFF7D8590) : const Color(0xFF6B7A8D),\n"
    "            )),\n"
    "          ]),\n"
    "        ),\n"
    "\n"
    "        const SizedBox(height: 24),\n"
    "\n"
    "        // Stats grid\n"
    "        GridView.count(\n"
    "          shrinkWrap: true,\n"
    "          physics: const NeverScrollableScrollPhysics(),\n"
    "          crossAxisCount: 2,\n"
    "          mainAxisSpacing: 10,\n"
    "          crossAxisSpacing: 10,\n"
    "          childAspectRatio: 1.5,\n"
    "          children: [\n"
    "            _SummaryTile('\u2696\ufe0f', '\u0627\u0644\u0648\u0632\u0646', '${weight.toStringAsFixed(1)} \u0643\u062c\u0645',\n"
    "              AppColors.halalGreen, card, border, isDark),\n"
    "            _SummaryTile('\U0001f4cf', '\u0627\u0644\u0637\u0648\u0644', '${height.toStringAsFixed(0)} \u0633\u0645',\n"
    "              AppColors.waterBlue, card, border, isDark),\n"
    "            _SummaryTile('\U0001f382', '\u0627\u0644\u0639\u0645\u0631', '$age \u0633\u0646\u0629',\n"
    "              AppColors.barakahGold, card, border, isDark),\n"
    "            _SummaryTile('\U0001f4ca', 'BMI', bmi.toStringAsFixed(1),\n"
    "              bmiColor, card, border, isDark),\n"
    "          ],\n"
    "        ),\n"
    "\n"
    "        const SizedBox(height: 14),\n"
    "\n"
    "        // Calorie target\n"
    "        Container(\n"
    "          padding: const EdgeInsets.all(18),\n"
    "          decoration: BoxDecoration(\n"
    "            gradient: const LinearGradient(\n"
    "              colors: [Color(0xFF0A6B4A), Color(0xFF00A86B)],\n"
    "              begin: Alignment.topLeft, end: Alignment.bottomRight,\n"
    "            ),\n"
    "            borderRadius: BorderRadius.circular(18),\n"
    "            boxShadow: [BoxShadow(\n"
    "              color: AppColors.sunnahGreen.withOpacity(0.3),\n"
    "              blurRadius: 16, offset: const Offset(0, 6),\n"
    "            )],\n"
    "          ),\n"
    "          child: Row(children: [\n"
    "            const Text('\U0001f525', style: TextStyle(fontSize: 36)),\n"
    "            const SizedBox(width: 14),\n"
    "            Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [\n"
    "              const Text('\u0647\u062f\u0641 \u0627\u0644\u0633\u0639\u0631\u0627\u062a \u0627\u0644\u064a\u0648\u0645\u064a', style: TextStyle(\n"
    "                fontFamily: 'Cairo', fontSize: 12, color: Colors.white70)),\n"
    "              Text('$kcal \u0633\u0639\u0631\u0629', style: const TextStyle(\n"
    "                fontFamily: 'Cairo', fontSize: 24,\n"
    "                fontWeight: FontWeight.w900, color: Colors.white,\n"
    "              )),\n"
    "              Text('\u0645\u062d\u0633\u0648\u0628 \u0644\u062c\u0633\u0645\u0643 \u0648\u0647\u062f\u0641\u0643', style: const TextStyle(\n"
    "                fontFamily: 'Cairo', fontSize: 11, color: Colors.white60)),\n"
    "            ])),\n"
    "          ]),\n"
    "        ),\n"
    "\n"
    "        const SizedBox(height: 14),\n"
    "\n"
    "        // Goal summary\n"
    "        Container(\n"
    "          padding: const EdgeInsets.all(14),\n"
    "          decoration: BoxDecoration(\n"
    "            color: card,\n"
    "            borderRadius: BorderRadius.circular(14),\n"
    "            border: Border.all(color: border, width: 0.5),\n"
    "          ),\n"
    "          child: Row(children: [\n"
    "            Text(FitnessGoal.values[goalIdx.clamp(0, 4)].emoji(),\n"
    "              style: const TextStyle(fontSize: 28)),\n"
    "            const SizedBox(width: 12),\n"
    "            Column(crossAxisAlignment: CrossAxisAlignment.start, children: [\n"
    "              Text('\u0647\u062f\u0641\u0643', style: TextStyle(\n"
    "                fontFamily: 'Cairo', fontSize: 11,\n"
    "                color: isDark ? const Color(0xFF7D8590) : const Color(0xFF6B7A8D),\n"
    "              )),\n"
    "              Text(FitnessGoal.values[goalIdx.clamp(0, 4)].nameAr(),\n"
    "                style: TextStyle(\n"
    "                  fontFamily: 'Cairo', fontSize: 15, fontWeight: FontWeight.w800,\n"
    "                  color: isDark ? Colors.white : const Color(0xFF1F2A1F),\n"
    "                )),\n"
    "            ]),\n"
    "          ]),\n"
    "        ),\n"
    "      ]),\n"
    "    );\n"
    "  }\n"
    "}\n"
    "\n"
    "class _SummaryTile extends StatelessWidget {\n"
    "  final String emoji, label, value;\n"
    "  final Color color, card, border;\n"
    "  final bool isDark;\n"
    "  const _SummaryTile(this.emoji, this.label, this.value,\n"
    "    this.color, this.card, this.border, this.isDark);\n"
    "\n"
    "  @override\n"
    "  Widget build(BuildContext context) {\n"
    "    return Container(\n"
    "      padding: const EdgeInsets.all(14),\n"
    "      decoration: BoxDecoration(\n"
    "        color: card,\n"
    "        borderRadius: BorderRadius.circular(14),\n"
    "        border: Border.all(color: border, width: 0.5),\n"
    "      ),\n"
    "      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [\n"
    "        Text(emoji, style: const TextStyle(fontSize: 22)),\n"
    "        const Spacer(),\n"
    "        Text(value, style: TextStyle(\n"
    "          fontFamily: 'Cairo', fontSize: 18,\n"
    "          fontWeight: FontWeight.w900, color: color,\n"
    "        )),\n"
    "        Text(label, style: TextStyle(\n"
    "          fontFamily: 'Cairo', fontSize: 10,\n"
    "          color: isDark ? const Color(0xFF7D8590) : const Color(0xFF6B7A8D),\n"
    "        )),\n"
    "      ]),\n"
    "    );\n"
    "  }\n"
    "}",

    # ── Replacement ────────────────────────────────────────────────────
    "  Widget build(BuildContext context) {\n"
    "    final isAr   = lang == 'ar' || lang == 'ur';\n"
    "    String t(String ar, String en) => isAr ? ar : en;\n"
    "    final isMale = gender == 'brothers';\n"
    "    final card   = isDark ? const Color(0xFF161B22) : Colors.white;\n"
    "    final border = isDark ? const Color(0xFF21262D) : const Color(0xFFE8E4DF);\n"
    "    final muted  = isDark ? const Color(0xFF7D8590) : const Color(0xFF6B7A8D);\n"
    "\n"
    "    // Quick BMI calculation\n"
    "    final hM  = height / 100;\n"
    "    final bmi = weight / (hM * hM);\n"
    "    final bmiColor = bmi < 18.5 ? AppColors.waterBlue\n"
    "      : bmi < 25 ? AppColors.halalGreen\n"
    "      : bmi < 30 ? AppColors.doubtOrange\n"
    "      : AppColors.haramRed;\n"
    "\n"
    "    // Calorie estimate\n"
    "    final bmr = isMale\n"
    "      ? 10 * weight + 6.25 * height - 5 * age + 5\n"
    "      : 10 * weight + 6.25 * height - 5 * age - 161;\n"
    "    final acts = ActivityLevel.values;\n"
    "    final mult = acts[activityIdx.clamp(0, acts.length - 1)].multiplier;\n"
    "    final kcal = (bmr * mult).round();\n"
    "    final goal = FitnessGoal.values[goalIdx.clamp(0, 4)];\n"
    "    final weightStr = isAr\n"
    "      ? '${weight.toStringAsFixed(1)} \u0643\u062c\u0645'\n"
    "      : '${weight.toStringAsFixed(1)} kg';\n"
    "    final heightStr = isAr\n"
    "      ? '${height.toStringAsFixed(0)} \u0633\u0645'\n"
    "      : '${height.toStringAsFixed(0)} cm';\n"
    "    final ageStr = isAr ? '$age \u0633\u0646\u0629' : '$age yrs';\n"
    "    final kcalStr = isAr ? '$kcal \u0633\u0639\u0631\u0629' : '$kcal kcal';\n"
    "\n"
    "    return SingleChildScrollView(\n"
    "      padding: const EdgeInsets.fromLTRB(24, 8, 24, 24),\n"
    "      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [\n"
    "\n"
    "        // Header\n"
    "        TweenAnimationBuilder<double>(\n"
    "          tween: Tween(begin: 0.0, end: 1.0),\n"
    "          duration: const Duration(milliseconds: 500),\n"
    "          curve: Curves.easeOut,\n"
    "          builder: (_, v, child) => Opacity(opacity: v,\n"
    "            child: Transform.translate(offset: Offset(0, 20 * (1 - v)), child: child)),\n"
    "          child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [\n"
    "            const Text('\U0001f389', style: TextStyle(fontSize: 44)),\n"
    "            const SizedBox(height: 8),\n"
    "            Text(t('\u0643\u0644 \u0634\u064a\u0621 \u062c\u0627\u0647\u0632!', 'All Set!'),\n"
    "              style: TextStyle(fontFamily: 'Cairo', fontSize: 28,\n"
    "                fontWeight: FontWeight.w900,\n"
    "                color: isDark ? Colors.white : const Color(0xFF1F2A1F))),\n"
    "            Text(t('\u0645\u0644\u0641\u0643 \u0627\u0644\u0634\u062e\u0635\u064a \u0645\u062d\u0633\u0648\u0628',\n"
    "                   'Your profile has been calculated'),\n"
    "              style: TextStyle(fontFamily: 'Cairo', fontSize: 13, color: muted)),\n"
    "          ]),\n"
    "        ),\n"
    "\n"
    "        const SizedBox(height: 24),\n"
    "\n"
    "        // Stats grid\n"
    "        GridView.count(\n"
    "          shrinkWrap: true,\n"
    "          physics: const NeverScrollableScrollPhysics(),\n"
    "          crossAxisCount: 2,\n"
    "          mainAxisSpacing: 10,\n"
    "          crossAxisSpacing: 10,\n"
    "          childAspectRatio: 1.5,\n"
    "          children: [\n"
    "            _SummaryTile('\u2696\ufe0f', t('\u0627\u0644\u0648\u0632\u0646', 'Weight'),\n"
    "              weightStr, AppColors.halalGreen, card, border, isDark),\n"
    "            _SummaryTile('\U0001f4cf', t('\u0627\u0644\u0637\u0648\u0644', 'Height'),\n"
    "              heightStr, AppColors.waterBlue, card, border, isDark),\n"
    "            _SummaryTile('\U0001f382', t('\u0627\u0644\u0639\u0645\u0631', 'Age'),\n"
    "              ageStr, AppColors.barakahGold, card, border, isDark),\n"
    "            _SummaryTile('\U0001f4ca', 'BMI',\n"
    "              bmi.toStringAsFixed(1), bmiColor, card, border, isDark),\n"
    "          ],\n"
    "        ),\n"
    "\n"
    "        const SizedBox(height: 14),\n"
    "\n"
    "        // Calorie target\n"
    "        Container(\n"
    "          padding: const EdgeInsets.all(18),\n"
    "          decoration: BoxDecoration(\n"
    "            gradient: const LinearGradient(\n"
    "              colors: [Color(0xFF0A6B4A), Color(0xFF00A86B)],\n"
    "              begin: Alignment.topLeft, end: Alignment.bottomRight,\n"
    "            ),\n"
    "            borderRadius: BorderRadius.circular(18),\n"
    "            boxShadow: [BoxShadow(\n"
    "              color: AppColors.sunnahGreen.withOpacity(0.3),\n"
    "              blurRadius: 16, offset: const Offset(0, 6),\n"
    "            )],\n"
    "          ),\n"
    "          child: Row(children: [\n"
    "            const Text('\U0001f525', style: TextStyle(fontSize: 36)),\n"
    "            const SizedBox(width: 14),\n"
    "            Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [\n"
    "              Text(t('\u0647\u062f\u0641 \u0627\u0644\u0633\u0639\u0631\u0627\u062a \u0627\u0644\u064a\u0648\u0645\u064a',\n"
    "                     'Daily Calorie Goal'),\n"
    "                style: const TextStyle(fontFamily: 'Cairo', fontSize: 12, color: Colors.white70)),\n"
    "              Text(kcalStr, style: const TextStyle(\n"
    "                fontFamily: 'Cairo', fontSize: 24,\n"
    "                fontWeight: FontWeight.w900, color: Colors.white)),\n"
    "              Text(t('\u0645\u062d\u0633\u0648\u0628 \u0644\u062c\u0633\u0645\u0643 \u0648\u0647\u062f\u0641\u0643',\n"
    "                     'Calculated for your body & goal'),\n"
    "                style: const TextStyle(fontFamily: 'Cairo', fontSize: 11, color: Colors.white60)),\n"
    "            ])),\n"
    "          ]),\n"
    "        ),\n"
    "\n"
    "        const SizedBox(height: 14),\n"
    "\n"
    "        // Goal summary\n"
    "        Container(\n"
    "          padding: const EdgeInsets.all(14),\n"
    "          decoration: BoxDecoration(\n"
    "            color: card,\n"
    "            borderRadius: BorderRadius.circular(14),\n"
    "            border: Border.all(color: border, width: 0.5),\n"
    "          ),\n"
    "          child: Row(children: [\n"
    "            Text(goal.emoji(), style: const TextStyle(fontSize: 28)),\n"
    "            const SizedBox(width: 12),\n"
    "            Column(crossAxisAlignment: CrossAxisAlignment.start, children: [\n"
    "              Text(t('\u0647\u062f\u0641\u0643', 'Your Goal'),\n"
    "                style: TextStyle(fontFamily: 'Cairo', fontSize: 11, color: muted)),\n"
    "              Text(isAr ? goal.nameAr() : goal.nameEn(),\n"
    "                style: TextStyle(fontFamily: 'Cairo', fontSize: 15,\n"
    "                  fontWeight: FontWeight.w800,\n"
    "                  color: isDark ? Colors.white : const Color(0xFF1F2A1F))),\n"
    "            ]),\n"
    "          ]),\n"
    "        ),\n"
    "      ]),\n"
    "    );\n"
    "  }\n"
    "}\n"
    "\n"
    "class _SummaryTile extends StatelessWidget {\n"
    "  final String emoji, label, value;\n"
    "  final Color color, card, border;\n"
    "  final bool isDark;\n"
    "  const _SummaryTile(this.emoji, this.label, this.value,\n"
    "    this.color, this.card, this.border, this.isDark);\n"
    "\n"
    "  @override\n"
    "  Widget build(BuildContext context) {\n"
    "    return Container(\n"
    "      padding: const EdgeInsets.all(14),\n"
    "      decoration: BoxDecoration(\n"
    "        color: card,\n"
    "        borderRadius: BorderRadius.circular(14),\n"
    "        border: Border.all(color: border, width: 0.5),\n"
    "      ),\n"
    "      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [\n"
    "        Text(emoji, style: const TextStyle(fontSize: 22)),\n"
    "        const Spacer(),\n"
    "        Text(value, style: TextStyle(\n"
    "          fontFamily: 'Cairo', fontSize: 18,\n"
    "          fontWeight: FontWeight.w900, color: color)),\n"
    "        Text(label, style: TextStyle(\n"
    "          fontFamily: 'Cairo', fontSize: 10,\n"
    "          color: isDark ? const Color(0xFF7D8590) : const Color(0xFF6B7A8D))),\n"
    "      ]),\n"
    "    );\n"
    "  }\n"
    "}",
    "onboarding: _SummaryPage + _SummaryTile bilingual")

print("\n── Fix 3c: _SummaryPage call site — pass lang ───────────────────────")

patch(ONBOARD,
    "      default: return _SummaryPage(\n"
    "        gender: _gender,\n"
    "        age: _age,\n"
    "        height: _height,\n"
    "        weight: _weight,\n"
    "        goalIdx: _goalIdx,\n"
    "        activityIdx: _activityIdx,\n"
    "        isDark: isDark,\n"
    "      );",
    "      default: return _SummaryPage(\n"
    "        gender: _gender, lang: lang,\n"
    "        age: _age,\n"
    "        height: _height,\n"
    "        weight: _weight,\n"
    "        goalIdx: _goalIdx,\n"
    "        activityIdx: _activityIdx,\n"
    "        isDark: isDark,\n"
    "      );",
    "onboarding: _SummaryPage call site pass lang")

# ── Fix 3d: FitnessGoal.nameEn() — add English name method ──────────
print("\n── Fix 3d: FitnessGoal.nameEn() — ensure English enum method exists ──")
# Check if nameEn already exists
with open("lib/data/models/models.dart", "r", encoding="utf-8") as f:
    models_src = f.read()

if "nameEn()" not in models_src:
    # Find nameAr and add nameEn right after
    old_m = "  String nameAr() {\n    switch (this) {\n      case FitnessGoal.weightLoss:     return '\u062e\u0633\u0627\u0631\u0629 \u0627\u0644\u0648\u0632\u0646';\n      case FitnessGoal.muscleGain:     return '\u0628\u0646\u0627\u0621 \u0627\u0644\u0639\u0636\u0644';\n      case FitnessGoal.maintenance:    return '\u0627\u0644\u062d\u0641\u0627\u0638 \u0639\u0644\u0649 \u0627\u0644\u0648\u0632\u0646';\n      case FitnessGoal.generalHealth:  return '\u0635\u062d\u0629 \u0639\u0627\u0645\u0629';\n      case FitnessGoal.islamicFitness: return '\u0644\u064a\u0627\u0642\u0629 \u0625\u0633\u0644\u0627\u0645\u064a\u0629';\n    }\n  }"
    new_m = (
        "  String nameAr() {\n    switch (this) {\n      case FitnessGoal.weightLoss:     return '\u062e\u0633\u0627\u0631\u0629 \u0627\u0644\u0648\u0632\u0646';\n      case FitnessGoal.muscleGain:     return '\u0628\u0646\u0627\u0621 \u0627\u0644\u0639\u0636\u0644';\n      case FitnessGoal.maintenance:    return '\u0627\u0644\u062d\u0641\u0627\u0638 \u0639\u0644\u0649 \u0627\u0644\u0648\u0632\u0646';\n      case FitnessGoal.generalHealth:  return '\u0635\u062d\u0629 \u0639\u0627\u0645\u0629';\n      case FitnessGoal.islamicFitness: return '\u0644\u064a\u0627\u0642\u0629 \u0625\u0633\u0644\u0627\u0645\u064a\u0629';\n    }\n  }\n"
        "  String nameEn() {\n    switch (this) {\n      case FitnessGoal.weightLoss:     return 'Weight Loss';\n      case FitnessGoal.muscleGain:     return 'Muscle Gain';\n      case FitnessGoal.maintenance:    return 'Maintenance';\n      case FitnessGoal.generalHealth:  return 'General Health';\n      case FitnessGoal.islamicFitness: return 'Islamic Fitness';\n    }\n  }"
    )
    if models_src.count(old_m) == 1:
        with open("lib/data/models/models.dart", "w", encoding="utf-8") as f:
            f.write(models_src.replace(old_m, new_m, 1))
        print("  [+] models: FitnessGoal.nameEn() added")
    else:
        print("  [~] models: nameAr anchor not found — nameEn may already exist or anchor changed")
else:
    print("  [~] models: nameEn() already present — skip")

# ── Fix 4: Complete Ramadan banner redesign ───────────────────────────
print("\n── Fix 4: Complete _RamadanBanner redesign ──────────────────────────")

OLD_BANNER_BUILD = (
    "  @override\n"
    "  Widget build(BuildContext context) {\n"
    "    String t(String ar, String en) => isAr ? ar : en;\n"
    "    final nowMins   = now.hour * 60 + now.minute;\n"
    "    final iftarMins = _iftarH * 60 + _iftarM;\n"
    "    final isFasting = nowMins >= _suhoorH * 60 + _suhoorM && nowMins < iftarMins;\n"
    "    final minsToIftar = ((iftarMins - nowMins) + 1440) % 1440;\n"
    "    final iftarSoon   = minsToIftar >= 1 && minsToIftar <= 15;\n"
    "    final ayah        = _ayahs[now.weekday % _ayahs.length];\n"
    "    final day         = _dayOfRamadan;\n"
    "    final sw          = MediaQuery.of(context).size.width;\n"
    "\n"
    "    // Star positions [x-fraction, y, size]\n"
    "    const stars = [\n"
    "      [0.06,  8.0, 5.0], [0.16,  4.0, 3.5], [0.30, 10.0, 4.5],\n"
    "      [0.45,  3.0, 4.0], [0.60,  7.0, 3.0], [0.75,  5.0, 5.5],\n"
    "      [0.88, 12.0, 4.0], [0.22, 20.0, 3.5], [0.52, 22.0, 4.5],\n"
    "      [0.80, 18.0, 3.5], [0.93,  9.0, 3.0], [0.38, 17.0, 4.0],\n"
    "    ];\n"
    "\n"
    "    return ClipRRect(\n"
    "      borderRadius: BorderRadius.circular(20),\n"
    "      child: Container(\n"
    "        decoration: BoxDecoration(\n"
    "          gradient: LinearGradient(\n"
    "            colors: isFasting\n"
    "              ? [const Color(0xFF080F20), const Color(0xFF0D1535), const Color(0xFF0A1A40)]\n"
    "              : [const Color(0xFF140A00), const Color(0xFF1E0E00), const Color(0xFF0F1020)],\n"
    "            begin: Alignment.topLeft, end: Alignment.bottomRight,\n"
    "          ),\n"
    "          borderRadius: BorderRadius.circular(20),\n"
    "          border: Border.all(\n"
    "            color: (iftarSoon ? Colors.orange : AppColors.barakahGold).withOpacity(0.5),\n"
    "            width: iftarSoon ? 2.0 : 1.5),\n"
    "          boxShadow: [BoxShadow(\n"
    "            color: (iftarSoon ? Colors.orange : AppColors.barakahGold).withOpacity(0.22),\n"
    "            blurRadius: 28, offset: const Offset(0, 8))],\n"
    "        ),\n"
    "        child: Stack(children: [\n"
    "\n"
    "          // Star particles\n"
    "          ...stars.map((s) => Positioned(\n"
    "            left: sw * (s[0] as double) - 18,\n"
    "            top:  s[1] as double,\n"
    "            child: Text('\u2736', style: TextStyle(\n"
    "              fontSize: s[2] as double,\n"
    "              color: AppColors.barakahGold.withOpacity(0.45))),\n"
    "          )),\n"
    "\n"
    "          // Golden shimmer orb top-right\n"
    "          Positioned(right: -30, top: -30, child: Container(\n"
    "            width: 130, height: 130,\n"
    "            decoration: BoxDecoration(\n"
    "              shape: BoxShape.circle,\n"
    "              gradient: RadialGradient(colors: [\n"
    "                AppColors.barakahGold.withOpacity(0.12), Colors.transparent])),\n"
    "          )),\n"
    "\n"
    "          // Iftar Soon glow pulse\n"
    "          if (iftarSoon) Positioned.fill(child: Container(\n"
    "            decoration: BoxDecoration(\n"
    "              borderRadius: BorderRadius.circular(20),\n"
    "              border: Border.all(color: Colors.orange.withOpacity(0.3), width: 3)),\n"
    "          )),\n"
    "\n"
    "          Padding(\n"
    "            padding: const EdgeInsets.fromLTRB(16, 14, 16, 12),\n"
    "            child: Column(children: [\n"
    "\n"
    "              // \u2500\u2500 Row 1: crescent + title + day badge \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
    "              Row(crossAxisAlignment: CrossAxisAlignment.center, children: [\n"
    "                ScaleTransition(\n"
    "                  scale: Tween<double>(begin: 0.92, end: 1.08).animate(moonAnim),\n"
    "                  child: Container(\n"
    "                    width: 58, height: 58,\n"
    "                    decoration: BoxDecoration(\n"
    "                      gradient: LinearGradient(\n"
    "                        colors: isFasting\n"
    "                          ? [const Color(0xFF1a237e), const Color(0xFF3949ab)]\n"
    "                          : [const Color(0xFFD4A017), const Color(0xFFFFD060)],\n"
    "                        begin: Alignment.topLeft, end: Alignment.bottomRight,\n"
    "                      ),\n"
    "                      shape: BoxShape.circle,\n"
    "                      boxShadow: [BoxShadow(\n"
    "                        color: (isFasting\n"
    "                          ? const Color(0xFF3949ab)\n"
    "                          : AppColors.barakahGold).withOpacity(0.6),\n"
    "                        blurRadius: 18, spreadRadius: 2)],\n"
    "                    ),\n"
    "                    child: Center(child: Text(\n"
    "                      isFasting ? '\u2605' : '\U0001f319',\n"
    "                      style: TextStyle(\n"
    "                        fontSize: isFasting ? 28 : 26,\n"
    "                        color: isFasting ? Colors.white : null))),\n"
    "                  ),\n"
    "                ),\n"
    "                const SizedBox(width: 12),\n"
    "                Expanded(child: Column(\n"
    "                    crossAxisAlignment: CrossAxisAlignment.start, children: [\n"
    "                  Text(t('\u0631\u0645\u0636\u0627\u0646 \u0643\u0631\u064a\u0645', 'Ramadan Kareem'),\n"
    "                    style: TextStyle(fontFamily: 'Cairo', fontSize: 20,\n"
    "                      fontWeight: FontWeight.w900,\n"
    "                      color: isFasting ? const Color(0xFF7986cb) : AppColors.barakahGold,\n"
    "                      letterSpacing: 0.3)),\n"
    "                  const SizedBox(height: 3),\n"
    "                  Row(children: [\n"
    "                    AnimatedContainer(\n"
    "                      duration: const Duration(milliseconds: 500),\n"
    "                      width: 8, height: 8,\n"
    "                      decoration: BoxDecoration(\n"
    "                        shape: BoxShape.circle,\n"
    "                        color: isFasting ? const Color(0xFF4caf50) : Colors.orange,\n"
    "                        boxShadow: [BoxShadow(\n"
    "                          color: (isFasting ? const Color(0xFF4caf50) : Colors.orange)\n"
    "                              .withOpacity(0.8),\n"
    "                          blurRadius: 8)]),\n"
    "                    ),\n"
    "                    const SizedBox(width: 6),\n"
    "                    Text(\n"
    "                      iftarSoon\n"
    "                        ? t('\u0642\u0631\u064a\u0628\u0627\u064b \u2014 \u0627\u0644\u0625\u0641\u0637\u0627\u0631 \u062e\u0644\u0627\u0644 \u062f\u0642\u0627\u0626\u0642 \U0001f964', 'Soon \u2014 Iftar in minutes \U0001f964')\n"
    "                        : isFasting\n"
    "                          ? t('\u0623\u0646\u062a \u0635\u0627\u0626\u0645 \u2014 \u062b\u0628\u062a \u0648\u0627\u062d\u062a\u0633\u0628 \U0001f90d', 'Fasting \u2014 stay strong \U0001f90d')\n"
    "                          : t('\u0648\u0642\u062a \u0627\u0644\u0625\u0641\u0637\u0627\u0631 \u2014 \u062a\u0642\u0628\u0651\u0644 \u0627\u0644\u0644\u0647 \U0001f33f', 'Iftar time \u2014 may Allah accept \U0001f33f'),\n"
    "                      style: TextStyle(fontFamily: 'Cairo', fontSize: 10.5,\n"
    "                        color: iftarSoon ? Colors.orange : Colors.white60)),\n"
    "                  ]),\n"
    "                ])),\n"
    "                // Day badge\n"
    "                Container(\n"
    "                  padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 8),\n"
    "                  decoration: BoxDecoration(\n"
    "                    color: AppColors.barakahGold.withOpacity(0.12),\n"
    "                    borderRadius: BorderRadius.circular(12),\n"
    "                    border: Border.all(color: AppColors.barakahGold.withOpacity(0.35))),\n"
    "                  child: Column(mainAxisSize: MainAxisSize.min, children: [\n"
    "                    Text(t('\u064a\u0648\u0645', 'Day'), style: const TextStyle(\n"
    "                      fontFamily: 'Cairo', fontSize: 8, color: Colors.white38)),\n"
    "                    Text('\u2728', style: const TextStyle(fontSize: 12)),\n"
    "                    Text('$day', style: const TextStyle(fontFamily: 'Cairo',\n"
    "                      fontSize: 16, fontWeight: FontWeight.w900,\n"
    "                      color: AppColors.barakahGold)),\n"
    "                    Text(t('\u0645\u0646 30', 'of 30'), style: const TextStyle(\n"
    "                      fontFamily: 'Cairo', fontSize: 7, color: Colors.white38)),\n"
    "                  ]),\n"
    "                ),\n"
    "              ]),\n"
    "\n"
    "              const SizedBox(height: 10),\n"
    "\n"
    "              // \u2500\u2500 Ramadan progress bar \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
    "              ClipRRect(\n"
    "                borderRadius: BorderRadius.circular(6),\n"
    "                child: LinearProgressIndicator(\n"
    "                  value: day / 30,\n"
    "                  minHeight: 6,\n"
    "                  backgroundColor: Colors.white.withOpacity(0.08),\n"
    "                  valueColor: AlwaysStoppedAnimation(\n"
    "                    isFasting ? const Color(0xFF3949ab) : AppColors.barakahGold),\n"
    "                ),\n"
    "              ),\n"
    "              Padding(\n"
    "                padding: const EdgeInsets.only(top: 4),\n"
    "                child: Row(\n"
    "                  mainAxisAlignment: MainAxisAlignment.spaceBetween,\n"
    "                  children: [\n"
    "                    Text(t('\u0627\u0644\u064a\u0648\u0645 1', 'Day 1'),\n"
    "                      style: const TextStyle(fontFamily: 'Cairo',\n"
    "                          fontSize: 8, color: Colors.white24)),\n"
    "                    Text(t('\u0627\u0644\u064a\u0648\u0645 $day', 'Day $day \u2605'),\n"
    "                      style: TextStyle(fontFamily: 'Cairo', fontSize: 8,\n"
    "                        fontWeight: FontWeight.w700,\n"
    "                        color: AppColors.barakahGold.withOpacity(0.8))),\n"
    "                    Text(t('\u064a\u0648\u0645 30', 'Day 30'),\n"
    "                      style: const TextStyle(fontFamily: 'Cairo',\n"
    "                          fontSize: 8, color: Colors.white24)),\n"
    "                  ],\n"
    "                ),\n"
    "              ),\n"
    "\n"
    "              const SizedBox(height: 12),\n"
    "              Divider(color: AppColors.barakahGold.withOpacity(0.18), height: 1),\n"
    "              const SizedBox(height: 12),\n"
    "\n"
    "              // \u2500\u2500 Iftar + Suhoor countdown chips \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
    "              Row(children: [\n"
    "                Expanded(child: _RamadanCountdownChip(\n"
    "                  emoji: '\U0001f305',\n"
    "                  label: t('\u0627\u0644\u0625\u0641\u0637\u0627\u0631 \u0628\u0639\u062f', 'Iftar in'),\n"
    "                  countdown: _cd(_iftarH, _iftarM),\n"
    "                  color: iftarSoon ? Colors.orange : AppColors.barakahGold,\n"
    "                  isPrimary: isFasting,\n"
    "                  pulse: iftarSoon,\n"
    "                )),\n"
    "                const SizedBox(width: 8),\n"
    "                Expanded(child: _RamadanCountdownChip(\n"
    "                  emoji: '\U0001f303',\n"
    "                  label: t('\u0627\u0644\u0633\u062d\u0648\u0631 \u0628\u0639\u062f', 'Suhoor in'),\n"
    "                  countdown: _cd(_suhoorH, _suhoorM),\n"
    "                  color: const Color(0xFF7986cb),\n"
    "                  isPrimary: !isFasting,\n"
    "                  pulse: false,\n"
    "                )),\n"
    "              ]),\n"
    "\n"
    "              const SizedBox(height: 10),\n"
    "\n"
    "              // \u2500\u2500 Dua / Ayah strip \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
    "              Container(\n"
    "                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 9),\n"
    "                decoration: BoxDecoration(\n"
    "                  color: Colors.white.withOpacity(0.04),\n"
    "                  borderRadius: BorderRadius.circular(10),\n"
    "                  border: Border.all(color: Colors.white.withOpacity(0.07))),\n"
    "                child: Row(children: [\n"
    "                  Text('\u2728', style: TextStyle(\n"
    "                    fontSize: 12, color: AppColors.barakahGold.withOpacity(0.8))),\n"
    "                  const SizedBox(width: 8),\n"
    "                  Expanded(child: Text(isAr ? ayah['ar']! : ayah['en']!,\n"
    "                    style: const TextStyle(fontFamily: 'Cairo', fontSize: 10,\n"
    "                        color: Colors.white54, height: 1.6),\n"
    "                    textAlign: TextAlign.center)),\n"
    "                  const SizedBox(width: 8),\n"
    "                  Text('\u2728', style: TextStyle(\n"
    "                    fontSize: 12, color: AppColors.barakahGold.withOpacity(0.8))),\n"
    "                ]),\n"
    "              ),\n"
    "            ]),\n"
    "          ),\n"
    "        ]),\n"
    "      ),\n"
    "    );\n"
    "  }\n"
    "}\n"
    "\n"
    "class _RamadanCountdownChip extends StatelessWidget {\n"
    "  final String emoji, label, countdown;\n"
    "  final Color color;\n"
    "  final bool isPrimary, pulse;\n"
    "  const _RamadanCountdownChip({\n"
    "    required this.emoji, required this.label,\n"
    "    required this.countdown, required this.color,\n"
    "    required this.isPrimary, required this.pulse,\n"
    "  });\n"
    "  @override\n"
    "  Widget build(BuildContext context) {\n"
    "    return Container(\n"
    "      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 12),\n"
    "      decoration: BoxDecoration(\n"
    "        gradient: isPrimary ? LinearGradient(colors: [\n"
    "          AppColors.barakahGold.withOpacity(0.24),\n"
    "          AppColors.barakahGold.withOpacity(0.10),\n"
    "        ], begin: Alignment.topLeft, end: Alignment.bottomRight) : null,\n"
    "        color: isPrimary ? null : Colors.white.withOpacity(0.06),\n"
    "        borderRadius: BorderRadius.circular(13),\n"
    "        border: Border.all(\n"
    "          color: isPrimary ? AppColors.barakahGold.withOpacity(0.58)\n"
    "                           : Colors.white.withOpacity(0.12),\n"
    "          width: isPrimary ? 1.5 : 1.0),\n"
    "      ),\n"
    "      child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [\n"
    "        Text(emoji, style: const TextStyle(fontSize: 22)),\n"
    "        const SizedBox(height: 4),\n"
    "        Text(label, style: TextStyle(fontFamily: 'Cairo', fontSize: 9,\n"
    "            color: isPrimary ? color.withOpacity(0.9) : Colors.white54)),\n"
    "        const SizedBox(height: 4),\n"
    "        Text(countdown, style: TextStyle(fontFamily: 'Cairo', fontSize: 17,\n"
    "            fontWeight: FontWeight.w900, color: isPrimary ? color : Colors.white60)),\n"
    "      ]),\n"
    "    );\n"
    "  }\n"
    "}"
)

NEW_BANNER_BUILD = (
    "  @override\n"
    "  Widget build(BuildContext context) {\n"
    "    String t(String ar, String en) => isAr ? ar : en;\n"
    "    final nowMins   = now.hour * 60 + now.minute;\n"
    "    final iftarMins = _iftarH * 60 + _iftarM;\n"
    "    final isFasting = nowMins >= _suhoorH * 60 + _suhoorM && nowMins < iftarMins;\n"
    "    final minsToIftar = ((iftarMins - nowMins) + 1440) % 1440;\n"
    "    final iftarSoon   = minsToIftar >= 1 && minsToIftar <= 15;\n"
    "    final ayah        = _ayahs[now.weekday % _ayahs.length];\n"
    "    final day         = _dayOfRamadan;\n"
    "    final sw          = MediaQuery.of(context).size.width;\n"
    "\n"
    "    // Gold accent palette\n"
    "    const gold        = Color(0xFFF0C040);\n"
    "    const goldDeep    = Color(0xFFC9963E);\n"
    "    const goldSoft    = Color(0xFFFFE082);\n"
    "    const indigo      = Color(0xFF4A5BC9);\n"
    "    const indigoDeep  = Color(0xFF303F9F);\n"
    "    final accentColor = iftarSoon ? Colors.deepOrange : isFasting ? indigo : gold;\n"
    "\n"
    "    // Star field\n"
    "    const stars = [\n"
    "      [0.07, 10.0, 4.0], [0.18,  3.5, 2.5], [0.32, 11.0, 3.5],\n"
    "      [0.50,  2.5, 3.0], [0.63,  8.5, 2.0], [0.78,  4.5, 4.5],\n"
    "      [0.90, 13.0, 3.0], [0.24, 21.0, 2.5], [0.55, 23.0, 3.5],\n"
    "      [0.82, 19.0, 2.5], [0.94,  7.0, 2.0], [0.40, 16.0, 3.0],\n"
    "    ];\n"
    "\n"
    "    return ClipRRect(\n"
    "      borderRadius: BorderRadius.circular(22),\n"
    "      child: Container(\n"
    "        decoration: BoxDecoration(\n"
    "          // Deep space gradient — changes warmth based on fasting state\n"
    "          gradient: LinearGradient(\n"
    "            colors: isFasting\n"
    "              ? [const Color(0xFF060A1E), const Color(0xFF0C1132),\n"
    "                 const Color(0xFF080D28), const Color(0xFF050818)]\n"
    "              : [const Color(0xFF12080A), const Color(0xFF1C0D00),\n"
    "                 const Color(0xFF10080A), const Color(0xFF0A0508)],\n"
    "            begin: Alignment.topLeft, end: Alignment.bottomRight,\n"
    "            stops: const [0.0, 0.35, 0.65, 1.0],\n"
    "          ),\n"
    "          borderRadius: BorderRadius.circular(22),\n"
    "          border: Border.all(\n"
    "            color: accentColor.withOpacity(iftarSoon ? 0.85 : 0.45),\n"
    "            width: iftarSoon ? 2.5 : 1.5),\n"
    "          boxShadow: [\n"
    "            BoxShadow(\n"
    "              color: accentColor.withOpacity(iftarSoon ? 0.40 : 0.20),\n"
    "              blurRadius: iftarSoon ? 36 : 24, spreadRadius: iftarSoon ? 2 : 0,\n"
    "              offset: const Offset(0, 6)),\n"
    "            BoxShadow(\n"
    "              color: Colors.black.withOpacity(0.45),\n"
    "              blurRadius: 20, offset: const Offset(0, 4)),\n"
    "          ],\n"
    "        ),\n"
    "        child: Stack(children: [\n"
    "\n"
    "          // ── Ambient glow orbs ──────────────────────────────\n"
    "          Positioned(right: -40, top: -40, child: Container(\n"
    "            width: 160, height: 160,\n"
    "            decoration: BoxDecoration(\n"
    "              shape: BoxShape.circle,\n"
    "              gradient: RadialGradient(colors: [\n"
    "                (isFasting ? indigo : gold).withOpacity(0.14),\n"
    "                Colors.transparent,\n"
    "              ])),\n"
    "          )),\n"
    "          Positioned(left: -30, bottom: -30, child: Container(\n"
    "            width: 110, height: 110,\n"
    "            decoration: BoxDecoration(\n"
    "              shape: BoxShape.circle,\n"
    "              gradient: RadialGradient(colors: [\n"
    "                goldDeep.withOpacity(0.10), Colors.transparent,\n"
    "              ])),\n"
    "          )),\n"
    "\n"
    "          // ── Star particles ─────────────────────────────────\n"
    "          ...stars.map((s) => Positioned(\n"
    "            left: sw * (s[0] as double) - 16,\n"
    "            top: s[1] as double,\n"
    "            child: Text('+', style: TextStyle(\n"
    "              fontSize: s[2] as double,\n"
    "              fontWeight: FontWeight.w900,\n"
    "              color: goldSoft.withOpacity(0.30))),\n"
    "          )),\n"
    "\n"
    "          // ── Iftar-soon full-border pulse ───────────────────\n"
    "          if (iftarSoon) Positioned.fill(child: IgnorePointer(\n"
    "            child: Container(decoration: BoxDecoration(\n"
    "              borderRadius: BorderRadius.circular(22),\n"
    "              border: Border.all(\n"
    "                color: Colors.deepOrange.withOpacity(0.28), width: 4))),\n"
    "          )),\n"
    "\n"
    "          // ── Main content ───────────────────────────────────\n"
    "          Padding(\n"
    "            padding: const EdgeInsets.fromLTRB(18, 16, 18, 14),\n"
    "            child: Column(children: [\n"
    "\n"
    "              // ─── Row 1: icon · title · day badge ───────────\n"
    "              Row(crossAxisAlignment: CrossAxisAlignment.center, children: [\n"
    "\n"
    "                // Animated moon/star orb\n"
    "                ScaleTransition(\n"
    "                  scale: Tween<double>(begin: 0.90, end: 1.10).animate(moonAnim),\n"
    "                  child: Container(\n"
    "                    width: 62, height: 62,\n"
    "                    decoration: BoxDecoration(\n"
    "                      shape: BoxShape.circle,\n"
    "                      gradient: LinearGradient(\n"
    "                        colors: isFasting\n"
    "                          ? [indigoDeep, const Color(0xFF5C6BC0)]\n"
    "                          : [goldDeep, const Color(0xFFFFD740)],\n"
    "                        begin: Alignment.topLeft, end: Alignment.bottomRight,\n"
    "                      ),\n"
    "                      boxShadow: [\n"
    "                        BoxShadow(\n"
    "                          color: (isFasting ? indigo : gold).withOpacity(0.65),\n"
    "                          blurRadius: 22, spreadRadius: 3),\n"
    "                        BoxShadow(\n"
    "                          color: Colors.black.withOpacity(0.35),\n"
    "                          blurRadius: 8, offset: const Offset(0, 3)),\n"
    "                      ],\n"
    "                    ),\n"
    "                    child: Center(child: Text(\n"
    "                      isFasting ? '\u2605' : '\U0001f319',\n"
    "                      style: TextStyle(\n"
    "                        fontSize: isFasting ? 30 : 28,\n"
    "                        color: Colors.white,\n"
    "                        shadows: [Shadow(\n"
    "                          color: Colors.black.withOpacity(0.4),\n"
    "                          blurRadius: 6)]))),\n"
    "                  ),\n"
    "                ),\n"
    "\n"
    "                const SizedBox(width: 14),\n"
    "\n"
    "                // Title + status\n"
    "                Expanded(child: Column(\n"
    "                  crossAxisAlignment: CrossAxisAlignment.start, children: [\n"
    "                  Text(t('\u0631\u0645\u0636\u0627\u0646 \u0643\u0631\u064a\u0645', 'Ramadan Kareem'),\n"
    "                    style: TextStyle(\n"
    "                      fontFamily: 'Cairo', fontSize: 21,\n"
    "                      fontWeight: FontWeight.w900,\n"
    "                      color: isFasting ? const Color(0xFF8C9EFF) : gold,\n"
    "                      letterSpacing: 0.5,\n"
    "                      shadows: [Shadow(\n"
    "                        color: (isFasting ? indigo : gold).withOpacity(0.5),\n"
    "                        blurRadius: 12)])),\n"
    "                  const SizedBox(height: 5),\n"
    "                  Row(children: [\n"
    "                    // Pulsing status dot\n"
    "                    Container(\n"
    "                      width: 7, height: 7,\n"
    "                      decoration: BoxDecoration(\n"
    "                        shape: BoxShape.circle,\n"
    "                        color: iftarSoon\n"
    "                          ? Colors.deepOrange\n"
    "                          : isFasting ? const Color(0xFF69F0AE) : Colors.orange,\n"
    "                        boxShadow: [BoxShadow(\n"
    "                          color: (iftarSoon ? Colors.deepOrange\n"
    "                            : isFasting ? const Color(0xFF69F0AE)\n"
    "                            : Colors.orange).withOpacity(0.9),\n"
    "                          blurRadius: 9)]),\n"
    "                    ),\n"
    "                    const SizedBox(width: 7),\n"
    "                    Flexible(child: Text(\n"
    "                      iftarSoon\n"
    "                        ? t('\u0642\u0631\u064a\u0628\u0627\u064b \u2014 \u0627\u0644\u0625\u0641\u0637\u0627\u0631 \u062e\u0644\u0627\u0644 \u062f\u0642\u0627\u0626\u0642 \U0001f964',\n"
    "                            'Iftar in minutes \u2014 get ready \U0001f964')\n"
    "                        : isFasting\n"
    "                          ? t('\u0623\u0646\u062a \u0635\u0627\u0626\u0645 \u2014 \u062b\u0628\u062a \u0648\u0627\u062d\u062a\u0633\u0628 \U0001f90d',\n"
    "                              'Fasting \u2014 stay strong \U0001f90d')\n"
    "                          : t('\u0648\u0642\u062a \u0627\u0644\u0625\u0641\u0637\u0627\u0631 \u2014 \u062a\u0642\u0628\u0651\u0644 \u0627\u0644\u0644\u0647 \U0001f33f',\n"
    "                              'Iftar time \u2014 may Allah accept \U0001f33f'),\n"
    "                      style: TextStyle(\n"
    "                        fontFamily: 'Cairo', fontSize: 10.5,\n"
    "                        color: iftarSoon\n"
    "                          ? Colors.deepOrange\n"
    "                          : Colors.white.withOpacity(0.6)),\n"
    "                    )),\n"
    "                  ]),\n"
    "                ])),\n"
    "\n"
    "                // Day badge\n"
    "                Container(\n"
    "                  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),\n"
    "                  decoration: BoxDecoration(\n"
    "                    gradient: LinearGradient(\n"
    "                      colors: [gold.withOpacity(0.18), gold.withOpacity(0.06)],\n"
    "                      begin: Alignment.topCenter, end: Alignment.bottomCenter,\n"
    "                    ),\n"
    "                    borderRadius: BorderRadius.circular(14),\n"
    "                    border: Border.all(color: gold.withOpacity(0.50), width: 1.2),\n"
    "                    boxShadow: [BoxShadow(\n"
    "                      color: gold.withOpacity(0.20), blurRadius: 12)],\n"
    "                  ),\n"
    "                  child: Column(mainAxisSize: MainAxisSize.min, children: [\n"
    "                    Text(t('\u064a\u0648\u0645', 'Day'),\n"
    "                      style: const TextStyle(fontFamily: 'Cairo',\n"
    "                        fontSize: 8, color: Colors.white38)),\n"
    "                    const SizedBox(height: 1),\n"
    "                    const Text('\u2728', style: TextStyle(fontSize: 11)),\n"
    "                    const SizedBox(height: 1),\n"
    "                    Text('$day',\n"
    "                      style: const TextStyle(fontFamily: 'Cairo',\n"
    "                        fontSize: 18, fontWeight: FontWeight.w900, color: gold)),\n"
    "                    Text(t('\u0645\u0646 30', 'of 30'),\n"
    "                      style: const TextStyle(fontFamily: 'Cairo',\n"
    "                        fontSize: 7, color: Colors.white38)),\n"
    "                  ]),\n"
    "                ),\n"
    "              ]),\n"
    "\n"
    "              const SizedBox(height: 14),\n"
    "\n"
    "              // ─── Progress bar ───────────────────────────────\n"
    "              Column(children: [\n"
    "                ClipRRect(\n"
    "                  borderRadius: BorderRadius.circular(8),\n"
    "                  child: LinearProgressIndicator(\n"
    "                    value: day / 30,\n"
    "                    minHeight: 7,\n"
    "                    backgroundColor: Colors.white.withOpacity(0.06),\n"
    "                    valueColor: AlwaysStoppedAnimation(\n"
    "                      isFasting ? const Color(0xFF5C6BC0) : gold),\n"
    "                  ),\n"
    "                ),\n"
    "                const SizedBox(height: 5),\n"
    "                Row(\n"
    "                  mainAxisAlignment: MainAxisAlignment.spaceBetween,\n"
    "                  children: [\n"
    "                    Text(t('1', '1'),\n"
    "                      style: TextStyle(fontFamily: 'Cairo',\n"
    "                        fontSize: 8.5, color: Colors.white.withOpacity(0.25))),\n"
    "                    Row(children: [\n"
    "                      Text('\u2605 ', style: TextStyle(fontSize: 8, color: gold.withOpacity(0.7))),\n"
    "                      Text(t('\u0627\u0644\u064a\u0648\u0645 $day', 'Day $day'),\n"
    "                        style: TextStyle(fontFamily: 'Cairo', fontSize: 8.5,\n"
    "                          fontWeight: FontWeight.w800,\n"
    "                          color: gold.withOpacity(0.9))),\n"
    "                    ]),\n"
    "                    Text('30',\n"
    "                      style: TextStyle(fontFamily: 'Cairo',\n"
    "                        fontSize: 8.5, color: Colors.white.withOpacity(0.25))),\n"
    "                  ],\n"
    "                ),\n"
    "              ]),\n"
    "\n"
    "              const SizedBox(height: 14),\n"
    "\n"
    "              // ─── Countdown chips ────────────────────────────\n"
    "              Row(children: [\n"
    "                Expanded(child: _RamadanCountdownChip(\n"
    "                  emoji: '\U0001f305',\n"
    "                  label: t('\u0627\u0644\u0625\u0641\u0637\u0627\u0631 \u0628\u0639\u062f', 'Iftar in'),\n"
    "                  countdown: _cd(_iftarH, _iftarM),\n"
    "                  accentColor: iftarSoon ? Colors.deepOrange : gold,\n"
    "                  isPrimary: isFasting,\n"
    "                  pulse: iftarSoon,\n"
    "                )),\n"
    "                const SizedBox(width: 10),\n"
    "                Expanded(child: _RamadanCountdownChip(\n"
    "                  emoji: '\U0001f303',\n"
    "                  label: t('\u0627\u0644\u0633\u062d\u0648\u0631 \u0628\u0639\u062f', 'Suhoor in'),\n"
    "                  countdown: _cd(_suhoorH, _suhoorM),\n"
    "                  accentColor: const Color(0xFF8C9EFF),\n"
    "                  isPrimary: !isFasting,\n"
    "                  pulse: false,\n"
    "                )),\n"
    "              ]),\n"
    "\n"
    "              const SizedBox(height: 12),\n"
    "\n"
    "              // ─── Ayah strip ─────────────────────────────────\n"
    "              Container(\n"
    "                padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),\n"
    "                decoration: BoxDecoration(\n"
    "                  gradient: LinearGradient(\n"
    "                    colors: [gold.withOpacity(0.07), gold.withOpacity(0.03)],\n"
    "                    begin: Alignment.topLeft, end: Alignment.bottomRight,\n"
    "                  ),\n"
    "                  borderRadius: BorderRadius.circular(12),\n"
    "                  border: Border.all(color: gold.withOpacity(0.18), width: 1)),\n"
    "                child: Row(children: [\n"
    "                  Text('\u2728', style: TextStyle(\n"
    "                    fontSize: 11, color: gold.withOpacity(0.75))),\n"
    "                  const SizedBox(width: 10),\n"
    "                  Expanded(child: Text(isAr ? ayah['ar']! : ayah['en']!,\n"
    "                    style: TextStyle(fontFamily: 'Cairo', fontSize: 10.5,\n"
    "                      color: Colors.white.withOpacity(0.60), height: 1.55,\n"
    "                      fontStyle: FontStyle.italic),\n"
    "                    textAlign: TextAlign.center)),\n"
    "                  const SizedBox(width: 10),\n"
    "                  Text('\u2728', style: TextStyle(\n"
    "                    fontSize: 11, color: gold.withOpacity(0.75))),\n"
    "                ]),\n"
    "              ),\n"
    "            ]),\n"
    "          ),\n"
    "        ]),\n"
    "      ),\n"
    "    );\n"
    "  }\n"
    "}\n"
    "\n"
    "// ── Redesigned countdown chip ─────────────────────────────────────────\n"
    "class _RamadanCountdownChip extends StatelessWidget {\n"
    "  final String emoji, label, countdown;\n"
    "  final Color accentColor;\n"
    "  final bool isPrimary, pulse;\n"
    "  const _RamadanCountdownChip({\n"
    "    required this.emoji, required this.label,\n"
    "    required this.countdown, required this.accentColor,\n"
    "    required this.isPrimary, required this.pulse,\n"
    "  });\n"
    "  @override\n"
    "  Widget build(BuildContext context) {\n"
    "    return Container(\n"
    "      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 13),\n"
    "      decoration: BoxDecoration(\n"
    "        gradient: isPrimary\n"
    "          ? LinearGradient(\n"
    "              colors: [\n"
    "                accentColor.withOpacity(0.22),\n"
    "                accentColor.withOpacity(0.07),\n"
    "              ],\n"
    "              begin: Alignment.topLeft, end: Alignment.bottomRight)\n"
    "          : null,\n"
    "        color: isPrimary ? null : Colors.white.withOpacity(0.05),\n"
    "        borderRadius: BorderRadius.circular(14),\n"
    "        border: Border.all(\n"
    "          color: isPrimary\n"
    "            ? accentColor.withOpacity(0.65)\n"
    "            : Colors.white.withOpacity(0.10),\n"
    "          width: isPrimary ? 1.5 : 1.0),\n"
    "        boxShadow: isPrimary ? [BoxShadow(\n"
    "          color: accentColor.withOpacity(pulse ? 0.40 : 0.18),\n"
    "          blurRadius: pulse ? 20 : 10)] : null,\n"
    "      ),\n"
    "      child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [\n"
    "        Text(emoji, style: const TextStyle(fontSize: 24)),\n"
    "        const SizedBox(height: 5),\n"
    "        Text(label,\n"
    "          style: TextStyle(fontFamily: 'Cairo', fontSize: 9.5,\n"
    "            color: isPrimary\n"
    "              ? accentColor.withOpacity(0.9)\n"
    "              : Colors.white.withOpacity(0.50))),\n"
    "        const SizedBox(height: 4),\n"
    "        Text(countdown,\n"
    "          style: TextStyle(\n"
    "            fontFamily: 'Cairo', fontSize: 20,\n"
    "            fontWeight: FontWeight.w900,\n"
    "            letterSpacing: 0.5,\n"
    "            color: isPrimary ? accentColor : Colors.white.withOpacity(0.65),\n"
    "            shadows: isPrimary ? [Shadow(\n"
    "              color: accentColor.withOpacity(0.5),\n"
    "              blurRadius: 10)] : null)),\n"
    "      ]),\n"
    "    );\n"
    "  }\n"
    "}"
)

patch(HOME, OLD_BANNER_BUILD, NEW_BANNER_BUILD, "home: complete Ramadan banner redesign")

print("")
if errors:
    print("ERRORS:")
    for e in errors:
        print(f"  !! {e}")
    sys.exit(1)
else:
    print("All patches applied OK")
