// ============================================================
//  l10n.dart — HalalCalorie Bilingual String System
//  Supports: Arabic (ar) + English (en)
//  Usage: L.of(context).appName
// ============================================================

import 'package:flutter/material.dart';
import 'providers.dart'; import'package:flutter_riverpod/flutter_riverpod.dart'; import'package:shared_preferences/shared_preferences.dart';

// ── Language Provider ──────────────────────────────────────
final languageProvider = StateNotifierProvider<LanguageNotifier, String>(
  (ref) => LanguageNotifier(),
);

class LanguageNotifier extends StateNotifier<String> { LanguageNotifier() : super('ar') {
    _load();
  }

  Future<void> _load() async {
    final p = await SharedPreferences.getInstance(); state = p.getString('language') ?? 'ar';
  }

  Future<void> set(String lang) async {
    state = lang;
    final p = await SharedPreferences.getInstance(); await p.setString('language', lang);
  } bool get isArabic => state =='ar';
}

// ── L shortcut ─────────────────────────────────────────────
class L {
  final String lang;
  const L._(this.lang);

  factory L.of(BuildContext context) {
    // We read from the widget tree via InheritedWidget trick
    // but simpler: pass lang string directly return const L._('ar');
  }

  static L fromLang(String lang) => L._(lang); bool get isAr => lang =='ar';

  String t(String ar, String en) => isAr ? ar : en;

  // ── App ─────────────────────────────────────────────────── String get appName        => t('HalalCalorie', 'HalalCalorie'); String get appTagline     => t('حلال في كل لقمة • سنة في كل خطوة', 'Halal in every bite • Sunnah in every step'); String get bismillah      => t('بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ', 'In the name of Allah, the Most Gracious');

  // ── Nav ─────────────────────────────────────────────────── String get navHome        => t('الرئيسية', 'Home'); String get navScanner     => t('ماسح', 'Scanner'); String get navNutrition   => t('تغذية', 'Nutrition'); String get navFitness     => t('لياقة', 'Fitness'); String get navHealth      => t('صحة', 'Health'); String get navBody        => t('جسمي', 'Body'); String get navProfile     => t('ملفي', 'Profile');

  // ── Onboarding ──────────────────────────────────────────── String get start          => t('ابدأ ✨', 'Start ✨'); String get next           => t('التالي', 'Next'); String get back           => t('رجوع', 'Back'); String get skip           => t('تخطي', 'Skip'); String get done           => t('تم ✓', 'Done ✓'); String get save           => t('حفظ', 'Save'); String get cancel         => t('إلغاء', 'Cancel'); String get yes            => t('نعم', 'Yes'); String get no             => t('لا', 'No'); String get thankYou       => t('شكراً لك 🤲', 'Thank You 🤲'); String get thankYouSub    => t('بارك الله فيك! سنُخصّص تجربتك بالكامل.', 'May Allah bless you! We will personalize everything for you.');

  // ── Language Selection ──────────────────────────────────── String get chooseLanguage => t('اختر اللغة', 'Choose Language'); String get arabic         => t('العربية', 'Arabic'); String get english        => t('الإنجليزية', 'English');

  // ── Gender ──────────────────────────────────────────────── String get chooseGender   => t('اختر طريقك', 'Choose Your Path'); String get genderNote     => t('هذا الاختيار دائم لضمان الخصوصية الكاملة', 'This choice is permanent to ensure full privacy'); String get brothers       => t('🧔 للرجال — Brothers', '🧔 Brothers — للرجال'); String get sisters        => t('🧕 للنساء — Sisters', '🧕 Sisters — للنساء'); String get genderWarning  => t('⚠️ لا يمكن تغيير هذا الاختيار', '⚠️ This choice cannot be changed');

  // ── Personal Info Questions ─────────────────────────────── String get personalInfo     => t('معلوماتك الشخصية', 'Your Personal Info'); String get personalInfoSub  => t('لنُخصّص تجربتك الصحية الكاملة — ${t("جميع البيانات مشفّرة وخاصة", "All data is encrypted & private")}', 'To personalize your full health experience — All data is encrypted & private'); String get qAge           => t('كم عمرك؟', 'How old are you?'); String get qAgeHint       => t('مثال: 25', 'e.g. 25'); String get qHeight        => t('ما طولك؟ (سم)', 'What is your height? (cm)'); String get qHeightHint    => t('مثال: 175', 'e.g. 175'); String get qWeight        => t('ما وزنك الحالي؟ (كجم)', 'What is your current weight? (kg)'); String get qWeightHint    => t('مثال: 70', 'e.g. 70'); String get qActivity      => t('مستوى نشاطك اليومي؟', 'What is your daily activity level?'); String get qGoal          => t('ما هدفك الرئيسي؟', 'What is your primary goal?'); String get qMealsPerDay   => t('كم وجبة تتناول يومياً؟', 'How many meals do you eat per day?'); String get qSleepHours    => t('كم ساعة تنام عادةً؟', 'How many hours do you usually sleep?'); String get qHealthConds   => t('هل لديك حالات صحية؟ (اختياري)', 'Any health conditions? (optional)'); String get qDietPref      => t('تفضيلاتك الغذائية؟', 'Your dietary preferences?'); String get qWaist         => t('محيط خصرك؟ (سم - اختياري)', 'Your waist circumference? (cm - optional)'); String get qWristSize     => t('حجم معصمك؟ (إطار الجسم)', 'Your wrist size? (body frame)');

  // ── Activity Levels ─────────────────────────────────────── String get actSedentary   => t('خامل (مكتبي)', 'Sedentary (desk job)'); String get actLight       => t('خفيف (1-3 أيام/أسبوع)', 'Lightly active (1-3 days/week)'); String get actModerate    => t('متوسط (3-5 أيام/أسبوع)', 'Moderately active (3-5 days/week)'); String get actActive      => t('نشيط (6-7 أيام/أسبوع)', 'Very active (6-7 days/week)'); String get actVeryActive  => t('رياضي (تمارين شاقة)', 'Athlete (intense exercise)');

  // ── Goals ───────────────────────────────────────────────── String get goalLoseWeight => t('خسارة الوزن', 'Lose Weight'); String get goalGainMuscle => t('بناء العضلات', 'Build Muscle'); String get goalMaintain   => t('الحفاظ على الوزن', 'Maintain Weight'); String get goalHealth     => t('تحسين الصحة العامة', 'Improve General Health'); String get goalRamadan    => t('الاستعداد لرمضان', 'Ramadan Preparation');

  // ── Diet Preferences ────────────────────────────────────── String get dietHalalOnly  => t('حلال فقط (افتراضي)', 'Halal Only (default)'); String get dietVeg        => t('نباتي + حلال', 'Vegetarian + Halal'); String get dietSunnah     => t('سنة نبوية', 'Sunnah Diet'); String get dietLowCarb    => t('قليل الكربوهيدرات', 'Low Carb');

  // ── Wrist / Frame ───────────────────────────────────────── String get wristSmall     => t('صغير (< 15 سم)', 'Small (< 15 cm)'); String get wristMedium    => t('متوسط (15-17 سم)', 'Medium (15-17 cm)'); String get wristLarge     => t('كبير (> 17 سم)', 'Large (> 17 cm)');

  // ── Health Conditions ───────────────────────────────────── String get condNone       => t('لا يوجد', 'None'); String get condDiabetes   => t('السكري', 'Diabetes'); String get condHypert     => t('ضغط الدم', 'Hypertension'); String get condHeart      => t('أمراض القلب', 'Heart Disease'); String get condThyroid    => t('الغدة الدرقية', 'Thyroid'); String get condOther      => t('أخرى', 'Other');

  // ── Body Metrics ────────────────────────────────────────── String get bodyMetrics    => t('مقاييس جسمك', 'Your Body Metrics'); String get bmi            => t('مؤشر كتلة الجسم', 'BMI'); String get bodyFat        => t('نسبة الدهون', 'Body Fat %'); String get muscleMass     => t('كتلة العضلات', 'Muscle Mass'); String get leanMass       => t('الكتلة النحيفة', 'Lean Body Mass'); String get bmr            => t('معدل الأيض الأساسي', 'Basal Metabolic Rate'); String get tdee           => t('إجمالي حرق السعرات', 'Total Daily Energy Expenditure'); String get idealWeight    => t('الوزن المثالي', 'Ideal Weight'); String get waterNeeded    => t('الماء اليومي المثالي', 'Daily Water Needed'); String get proteinNeeded  => t('البروتين اليومي', 'Daily Protein'); String get calorieGoal    => t('هدف السعرات', 'Calorie Goal');

  // ── Units ───────────────────────────────────────────────── String get kg             => t('كجم', 'kg'); String get cm             => t('سم', 'cm'); String get kcal           => t('سعرة حرارية', 'kcal'); String get grams          => t('جرام', 'g'); String get liters         => t('لتر', 'L'); String get years          => t('سنة', 'years'); String get hours          => t('ساعة', 'hrs'); String get perDay         => t('/ يوم', '/ day');

  // ── BMI Categories ──────────────────────────────────────── String get bmiUnder       => t('نقص وزن', 'Underweight'); String get bmiNormal      => t('وزن مثالي ✓', 'Normal ✓'); String get bmiOver        => t('زيادة وزن', 'Overweight'); String get bmiObese       => t('سمنة', 'Obese');

  // ── Home ───────────────────────────────────────────────── String get greetingMale   => t('السلام عليكم أخي 👋', 'Peace be upon you, brother 👋'); String get greetingFemale => t('السلام عليكم أختي 👋', 'Peace be upon you, sister 👋'); String get nextPrayer     => t('القادم', 'Next Prayer'); String get todayCalories  => t('سعرات اليوم', "Today's Calories"); String get streakDays     => t('يوم متتالي', 'day streak'); String get zakatSaved     => t('زكاة محفوظة', 'Zakat Saved'); String get quickActions   => t('ابدأ الآن', 'Start Now');

  // ── Nutrition ───────────────────────────────────────────── String get calories       => t('السعرات', 'Calories'); String get recipes        => t('الوصفات', 'Recipes'); String get aiPlanner      => t('مخطط AI', 'AI Planner'); String get addMeal        => t('+ أضف وجبة', '+ Add Meal'); String get mealLog        => t('وجبات اليوم', "Today's Meals"); String get noMeals        => t('لم تُسجّل أي وجبات اليوم', 'No meals logged today'); String get quickAdd       => t('إضافة سريعة', 'Quick Add'); String get customEntry    => t('إدخال مخصص', 'Custom Entry'); String get foodName       => t('اسم الطعام', 'Food Name'); String get addToTracker   => t('✓ أضف للعداد', '✓ Add to Tracker'); String get remaining      => t('متبقي', 'Remaining'); String get consumed       => t('مُستهلك', 'Consumed'); String get goal           => t('الهدف', 'Goal'); String get editGoal       => t('✏️ تعديل الهدف', '✏️ Edit Goal'); String get carbs          => t('كربوهيدرات', 'Carbs'); String get protein        => t('بروتين', 'Protein'); String get fat            => t('دهون', 'Fat');

  // ── Scanner ─────────────────────────────────────────────── String get halalScanner   => t('الماسح الحلال', 'Halal Scanner'); String get scanHistory    => t('السجل', 'History'); String get enterBarcode   => t('أدخل الباركود يدوياً...', 'Enter barcode manually...'); String get tryProducts    => t('جرّب هذه المنتجات:', 'Try these products:'); String get randomScan     => t('📷 مسح عشوائي', '📷 Random Scan'); String get scanAgain      => t('📷 مسح آخر', '📷 Scan Again'); String get scanHistoryTitle => t('سجل الماسحات', 'Scan History'); String get noScansYet     => t('لا توجد ماسحات بعد', 'No scans yet'); String get product        => t('المنتج', 'Product'); String get brand          => t('الماركة', 'Brand'); String get barcode        => t('الباركود', 'Barcode'); String get halal          => t('حلال ✓', 'Halal ✓'); String get doubtful       => t('مشبوه ⚠️', 'Doubtful ⚠️'); String get haram          => t('حرام ✕', 'Haram ✕'); String get unknown        => t('غير معروف ?', 'Unknown ?'); String get dailyLimit     => t('وصلت الحد اليومي', 'Daily Limit Reached'); String get scanLimitNote  => t('استخدمت ١٠ ماسحات اليوم', 'You have used 10 scans today');

  // ── Fitness ─────────────────────────────────────────────── String get islamicFitness => t('اللياقة الإسلامية', 'Islamic Fitness'); String get brothersMode   => t('وضع الرجال — بدون موسيقى', "Brothers'Mode — No Music"); String get sistersMode    => t('وضع النساء — محتشم دائماً', "Sisters'Mode — Always Modest"); String get remaining2     => t('متبقي', 'remaining'); String get startWorkout   => t('▶ ابدأ', '▶ Start'); String get pauseWorkout   => t('⏸ إيقاف', '⏸ Pause'); String get markDone       => t('✓ أكملت', '✓ Completed'); String get excellentWork  => t('أحسنت!', 'Excellent!'); String get blessYou       => t('بارك الله فيك 🤲', 'May Allah bless you 🤲'); String get backToWorkouts => t('العودة للتمارين', 'Back to Workouts'); String get advancedPlans  => t('١٨٠ خطة متقدمة 🔒', '180 Advanced Plans 🔒'); String get upgrade        => t('ترقية', 'Upgrade');

  // ── Health ──────────────────────────────────────────────── String get healthWellness => t('الصحة والعافية', 'Health & Wellness'); String get tracking       => t('تتبع', 'Tracking'); String get calculators    => t('حاسبات', 'Calculators'); String get articles       => t('مقالات', 'Articles'); String get waterToday     => t('الماء اليومي', 'Daily Water'); String get sleep          => t('النوم', 'Sleep'); String get steps          => t('الخطوات', 'Steps'); String get mood           => t('المزاج', 'Mood'); String get heartRate      => t('معدل النبض', 'Heart Rate'); String get addCup         => t('+ كوب 💧', '+ Cup 💧'); String get removeCup      => t('− كوب', '− Cup'); String get sleepGoal      => t('الهدف: ٨ ساعات للبالغين', 'Goal: 8 hrs for adults'); String get stepsFrom      => t('خطوة من', 'steps of'); String get moodLabel      => t('مزاجك اليوم', "Today's Mood"); String get moodRecorded   => t('سجّلت مزاجك', 'Mood recorded'); String get bmiCalc        => t('حاسبة BMI', 'BMI Calculator'); String get calcBmi        => t('احسب BMI', 'Calculate BMI'); String get burnedCalories => t('سعرات محروقة في ٣٠ دقيقة', 'Calories Burned in 30 min'); String get islamicArticles => t('مقالات صحية إسلامية', 'Islamic Health Articles'); String get tapToRead      => t('اضغط على أي مقال للقراءة', 'Tap any article to read'); String get normalRange    => t('المعدل الطبيعي: ٦٠-١٠٠', 'Normal range: 60-100'); String get measure        => t('🔄 قياس', '🔄 Measure');

  // ── Body Screen ─────────────────────────────────────────── String get myBody         => t('مقاييس جسمي', 'My Body Metrics'); String get overview       => t('نظرة عامة', 'Overview'); String get details        => t('تفاصيل', 'Details'); String get nutrition2     => t('التغذية', 'Nutrition'); String get premiumOnly    => t('بريميوم فقط 🔒', 'Premium Only 🔒'); String get unlockPremium  => t('افتح بريميوم لرؤية التفاصيل الدقيقة', 'Unlock Premium to see precise details'); String get yourBMI        => t('مؤشر كتلة جسمك', 'Your BMI'); String get fatPercent     => t('نسبة الدهون %', 'Body Fat %'); String get muscleKg       => t('كتلة العضلات', 'Muscle Mass'); String get leanBodyMass   => t('الكتلة النحيفة', 'Lean Body Mass'); String get basalRate      => t('معدل الأيض الأساسي', 'Basal Metabolic Rate'); String get totalEnergy    => t('إجمالي الحرق اليومي', 'Total Daily Calorie Burn'); String get proteinTarget  => t('هدف البروتين اليومي', 'Daily Protein Target'); String get carbsTarget    => t('هدف الكربوهيدرات', 'Daily Carbs Target'); String get fatTarget      => t('هدف الدهون الصحية', 'Daily Fat Target'); String get waterTarget    => t('الماء اليومي المثالي', 'Ideal Daily Water'); String get updateBody     => t('تحديث بياناتي', 'Update My Data'); String get bodyUpdated    => t('تم تحديث البيانات ✓', 'Data Updated ✓'); String get weightProgress => t('تقدم الوزن', 'Weight Progress'); String get currentWeight  => t('الوزن الحالي', 'Current Weight'); String get targetWeight   => t('الوزن المستهدف', 'Target Weight'); String get toGoal         => t('للوصول للهدف', 'to reach goal');

  // ── Profile ─────────────────────────────────────────────── String get myProfile      => t('ملفي الشخصي', 'My Profile'); String get islamicBrother => t('مسلم', 'Muslim'); String get islamicSister  => t('مسلمة', 'Muslimah'); String get brothersMode2  => t('وضع الرجال', "Brothers'Mode"); String get sistersMode2   => t('وضع النساء', "Sisters'Mode"); String get premium        => t('بريميوم ⭐', 'Premium ⭐'); String get streakDays2    => t('أيام التتابع', 'Streak Days'); String get waterCups      => t('الماء', 'Water'); String get sleepHrs       => t('النوم', 'Sleep'); String get upgradeNow     => t('ترقية إلى بريميوم', 'Upgrade to Premium'); String get upgradeDesc    => t('ماسحات غير محدودة + ١٨٠ تمرين + مخطط AI', 'Unlimited scans + 180 workouts + AI planner'); String get defaultCity    => t('المدينة الافتراضية', 'Default City'); String get nightMode      => t('الوضع الليلي', 'Night Mode'); String get dayMode        => t('الوضع النهاري', 'Day Mode'); String get privacyPolicy  => t('سياسة الخصوصية', 'Privacy Policy'); String get aboutApp       => t('حول التطبيق', 'About App'); String get signOut        => t('تسجيل الخروج', 'Sign Out'); String get signOutConfirm => t('هل أنت متأكد من تسجيل الخروج؟', 'Are you sure you want to sign out?'); String get chooseCity     => t('اختر مدينتك', 'Choose Your City'); String get language       => t('اللغة', 'Language');

  // ── Paywall ─────────────────────────────────────────────── String get upgradePremium => t('ترقية بريميوم', 'Upgrade to Premium'); String get fullPower      => t('اكتشف القوة الكاملة للسنة', 'Unlock the Full Power of Sunnah'); String get restore        => t('استعادة', 'Restore'); String get choosePlan     => t('اختر خطتك:', 'Choose Your Plan:'); String get subscribeNow   => t('اشترك الآن', 'Subscribe Now'); String get noHiddenFees   => t('لا رسوم خفية • لا ربا • دفع آمن', 'No hidden fees • No riba • Secure payment'); String get halalBadge     => t('١٠٠٪ حلال', '100% Halal'); String get privacy        => t('خصوصية', 'Privacy'); String get freeCanccel    => t('إلغاء مجاني', 'Free Cancel'); String get mostPopular    => t('الأكثر شعبية', 'Most Popular'); String get saving30       => t('توفير ٣٠٪', 'Save 30%'); String get monthly        => t('شهري', 'Monthly'); String get yearly         => t('سنوي', 'Yearly'); String get lifetime       => t('مدى الحياة', 'Lifetime'); String get perMonth       => t('شهر', 'month'); String get perYear        => t('سنة', 'year'); String get once           => t('مرة', 'once');
}
